apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: rolandsankara/udagram-api-feed:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: env-vars
        - secretRef:
            name: env-secrets
        - secretRef:
            name: aws-secrets
        resources:
          requests:
            memory: "64Mi"
            cpu: "300m"
          limits:
            memory: "1024Mi"
            cpu: "550m"
        ports:
        - containerPort: 8080
